apiVersion: v1
kind: ConfigMap
metadata:
  name: hpa-config
data:
  deployments.yaml: |
    - name: dep1
    - name: dep2
      minReplicas: 2
      maxReplicas: 6
  status.yaml: |
    - name: dep1
      replicas: 1
    - name: dep2
      replicas: 3
