---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep2
  name: dep2
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep2
  template:
    metadata:
      labels:
        app: dep2
    spec:
      containers:
        - image: docker.io/library/nursed-test:t1
          name: dep2
