---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep2
  name: dep2
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep2
  template:
    metadata:
      labels:
        app: dep2
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - image: docker.io/library/nursed-test:t1
          name: dep2
          ports:
          - name: metrics
            containerPort: 8080
            protocol: TCP
